name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal

    - uses: Swatinem/rust-cache@v2

    - run: rustup target add wasm32-unknown-unknown

    - name: Install Nasm
      run: sudo apt install -y nasm

    - uses: cargo-bins/cargo-binstall@main

    - name: Install Dixous-CLI
      run: cargo binstall dioxus-cli --version 0.6.3

    - name: Generate Tailwind CSS
      uses: ZoeyVid/tailwindcss-update@v1.4.0
      with:
        input: input.css
        output: assets/tailwind.css
        params: "--minify"

    - name: Create .env File
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Build Web Page
      run: dx build --platform web --release

    - name: Deploy to Cloudflare Page
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy target/dx/toaster/release/web/public --project-name=toaster --production